export default function Sidebar({ aktifSayfa, setAktifSayfa, sunucuDurumu }) {
  const menus = [['bilgi','Sistem Bilgisi','M13 16h-1v-4h-1m1-4h.01'],['kontrol','Donanım Kontrolü','M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4'],['grafik','Canlı Sinyal Akışı','M7 12l3-3 3 3 4-4'],['loglar','Sistem Logları','M4 6h16M4 10h16M4 14h16M4 18h16']];
  const baglanti = sunucuDurumu === 'BAĞLANILIYOR...'
    ? { metin: 'Bağlantı Bekleniyor', renk: 'text-amber-400', nokta: 'bg-amber-400' }
    : sunucuDurumu === 'ÇEVRİMİÇİ'
      ? { metin: 'Bağlantı Sağlandı', renk: 'text-emerald-400', nokta: 'bg-emerald-400' }
      : { metin: 'Bağlantı Yok', renk: 'text-red-400', nokta: 'bg-red-400' };
  return <aside className="w-72 bg-slate-900 border-r border-slate-800 flex flex-col shadow-2xl z-20"><div className="p-6 border-b border-slate-800"><h1 className="text-2xl font-extrabold text-white tracking-tight flex items-center gap-2">Cyber<span className="text-indigo-500">Hunter</span></h1><p className="text-xs text-slate-500 mt-1 font-medium tracking-widest">KONTROL PANELİ</p></div><nav className="flex-1 p-4 flex flex-col gap-2">{menus.map(([id,label,path]) => <button key={id} onClick={() => setAktifSayfa(id)} className={`px-4 py-3 rounded-xl text-left font-medium transition-all flex items-center gap-3 ${aktifSayfa === id ? 'bg-indigo-500/20 text-indigo-400 border border-indigo-500/30' : 'hover:bg-slate-800/50 text-slate-400 hover:text-slate-200 border border-transparent'}`}><svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d={path}/></svg>{label}</button>)}</nav><div className="p-4 border-t border-slate-800 bg-slate-900/50"><div className="flex items-center gap-3"><div className="w-9 h-9 rounded-full bg-indigo-900/50 text-indigo-400 flex items-center justify-center text-sm font-bold border border-indigo-500/30">Ö</div><div><div className="text-sm font-bold text-white">Ömer</div><div className={`text-xs flex items-center gap-1.5 mt-0.5 ${baglanti.renk}`}><span className={`w-1.5 h-1.5 rounded-full ${baglanti.nokta} ${sunucuDurumu === 'BAĞLANILIYOR...' ? 'animate-pulse' : ''}`}></span>{baglanti.metin}</div></div></div></div></aside>;
}
