"""initial postgresql schema

Revision ID: 6b9850c2d44d
Revises: 
Create Date: 2026-07-26 15:29:58.212049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9850c2d44d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CihazEmirleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('komut', sa.String(), nullable=True),
    sa.Column('durum', sa.String(), nullable=True),
    sa.Column('olusturulma_zamani', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('encryption_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CihazEmirleri_device_id'), 'CihazEmirleri', ['device_id'], unique=False)
    op.create_index(op.f('ix_CihazEmirleri_id'), 'CihazEmirleri', ['id'], unique=False)
    op.create_table('LedLoglari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('led', sa.String(), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=True),
    sa.Column('device_timestamp', sa.BigInteger(), nullable=True),
    sa.Column('nonce', sa.String(), nullable=True),
    sa.Column('server_received_at', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('encryption_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_LedLoglari_device_id'), 'LedLoglari', ['device_id'], unique=False)
    op.create_index(op.f('ix_LedLoglari_id'), 'LedLoglari', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrade is intentionally unsupported for the initial schema.")