import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import EmptyState from '../components/EmptyState';

export default function LiveSignalsPage({ grafikVerileri, sunucuDurumu }) {
  const baglanti = sunucuDurumu === 'BAĞLANILIYOR...'
    ? { metin: 'Bağlanıyor', stil: 'border-amber-500/20 bg-amber-500/10 text-amber-400', nokta: 'bg-amber-400 animate-pulse' }
    : sunucuDurumu === 'ÇEVRİMİÇİ'
      ? { metin: 'Çevrimiçi', stil: 'border-emerald-500/20 bg-emerald-500/10 text-emerald-400', nokta: 'bg-emerald-400' }
      : { metin: 'Çevrimdışı', stil: 'border-red-500/20 bg-red-500/10 text-red-400', nokta: 'bg-red-400' };
  return <div className="w-full h-full bg-slate-900 rounded-3xl p-8 border border-slate-800 shadow-lg flex flex-col animate-fade-in"><div className="flex justify-between items-center mb-8"><h2 className="text-xl font-bold text-white">Canlı Sinyal Akışı</h2><span className={`flex items-center gap-2 text-sm font-semibold px-4 py-1.5 rounded-full border ${baglanti.stil}`}><span className={`h-2 w-2 rounded-full ${baglanti.nokta}`}></span>{baglanti.metin}</span></div><div className="flex-1 w-full h-full min-h-[400px]">{sunucuDurumu === 'BAĞLANILIYOR...' ? <EmptyState baslik="Sunucuya bağlanılıyor" aciklama="CyberHunter servisleri kontrol ediliyor."/> : sunucuDurumu === 'ÇEVRİMDIŞI' ? <EmptyState baslik="Sunucu bağlantısı bulunamadı" aciklama="Backend servisi çalıştırıldığında canlı sinyal verileri burada gösterilecektir."/> : grafikVerileri.length === 0 ? <EmptyState baslik="Canlı veri bekleniyor" aciklama="Sunucu bağlantısı aktif ancak ESP32 tarafından henüz sinyal verisi gönderilmedi."/> : <ResponsiveContainer width="100%" height="100%"><LineChart data={grafikVerileri} margin={{top:10,right:30,bottom:0,left:-10}}><CartesianGrid strokeDasharray="3 3" stroke="#334155" vertical={false}/><XAxis dataKey="time" stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} dy={10}/><YAxis stroke="#64748b" fontSize={12} tickLine={false} axisLine={false} dx={-10}/><Tooltip contentStyle={{backgroundColor:'#020617',borderRadius:'12px',border:'1px solid #1e293b',color:'#f8fafc'}} itemStyle={{color:'#e2e8f0',fontWeight:'500'}}/><Legend verticalAlign="top" height={40} iconType="circle" wrapperStyle={{fontSize:'14px',fontWeight:'500',color:'#94a3b8'}}/><Line type="monotone" name="ESP32 Gelen Sinyal" dataKey="gelenSinyal" stroke="#6366f1" strokeWidth={3}/><Line type="monotone" name="Giden Komut" dataKey="gidenKomut" stroke="#10b981" strokeWidth={3}/></LineChart></ResponsiveContainer>}</div></div>;
}
